# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregate_across_cells <- function(x, groupings, nthreads) {
    .Call('_scran_chan_aggregate_across_cells', PACKAGE = 'scran.chan', x, groupings, nthreads)
}

build_nn_index <- function(data, approximate) {
    .Call('_scran_chan_build_nn_index', PACKAGE = 'scran.chan', data, approximate)
}

find_nearest_neighbors <- function(index, k, nthreads) {
    .Call('_scran_chan_find_nearest_neighbors', PACKAGE = 'scran.chan', index, k, nthreads)
}

query_nearest_neighbors <- function(query, index, k, nthreads) {
    .Call('_scran_chan_query_nearest_neighbors', PACKAGE = 'scran.chan', query, index, k, nthreads)
}

find_nearest_neighbor_indices <- function(index, k, nthreads) {
    .Call('_scran_chan_find_nearest_neighbor_indices', PACKAGE = 'scran.chan', index, k, nthreads)
}

cluster_kmeans <- function(data, nclusters, init_method, seed, nthreads) {
    .Call('_scran_chan_cluster_kmeans', PACKAGE = 'scran.chan', data, nclusters, init_method, seed, nthreads)
}

cluster_snn_graph <- function(nnidx, weight_scheme, method, resolution, steps, use_cpm, seed, nthreads) {
    .Call('_scran_chan_cluster_snn_graph', PACKAGE = 'scran.chan', nnidx, weight_scheme, method, resolution, steps, use_cpm, seed, nthreads)
}

combine_matrix <- function(x, byrow) {
    .Call('_scran_chan_combine_matrix', PACKAGE = 'scran.chan', x, byrow)
}

downsample_by_neighbors <- function(data, k, approximate, nthreads) {
    .Call('_scran_chan_downsample_by_neighbors', PACKAGE = 'scran.chan', data, k, approximate, nthreads)
}

filter_cells <- function(x, discard) {
    .Call('_scran_chan_filter_cells', PACKAGE = 'scran.chan', x, discard)
}

initialize_from_blocks_CSC <- function(nr, nc, is_integer) {
    .Call('_scran_chan_initialize_from_blocks_CSC', PACKAGE = 'scran.chan', nr, nc, is_integer)
}

initialize_from_blocks_CSR <- function(nr, nc, is_integer) {
    .Call('_scran_chan_initialize_from_blocks_CSR', PACKAGE = 'scran.chan', nr, nc, is_integer)
}

add_new_block_CSC <- function(ptr0, rows, columns, values, ncolumns) {
    .Call('_scran_chan_add_new_block_CSC', PACKAGE = 'scran.chan', ptr0, rows, columns, values, ncolumns)
}

add_new_block_CSR <- function(ptr0, rows, columns, values, nrows) {
    .Call('_scran_chan_add_new_block_CSR', PACKAGE = 'scran.chan', ptr0, rows, columns, values, nrows)
}

finalize_all_blocks_CSC <- function(ptr0) {
    .Call('_scran_chan_finalize_all_blocks_CSC', PACKAGE = 'scran.chan', ptr0)
}

finalize_all_blocks_CSR <- function(ptr0) {
    .Call('_scran_chan_finalize_all_blocks_CSR', PACKAGE = 'scran.chan', ptr0)
}

initialize_from_hdf5 <- function(file, name, nrow, ncol, byrow, forced) {
    .Call('_scran_chan_initialize_from_hdf5', PACKAGE = 'scran.chan', file, name, nrow, ncol, byrow, forced)
}

initialize_from_memory <- function(x, i, p, nrow, ncol, no_copy, byrow, forced) {
    .Call('_scran_chan_initialize_from_memory', PACKAGE = 'scran.chan', x, i, p, nrow, ncol, no_copy, byrow, forced)
}

log_norm_counts <- function(x, size_factors, batch, batch_mode, nthreads) {
    .Call('_scran_chan_log_norm_counts', PACKAGE = 'scran.chan', x, size_factors, batch, batch_mode, nthreads)
}

mnn_correct <- function(x, batch, k, nmads, nthreads, mass_cap, order, ref_policy, approximate) {
    .Call('_scran_chan_mnn_correct', PACKAGE = 'scran.chan', x, batch, k, nmads, nthreads, mass_cap, order, ref_policy, approximate)
}

model_gene_var <- function(x, batch, span, nthreads) {
    .Call('_scran_chan_model_gene_var', PACKAGE = 'scran.chan', x, batch, span, nthreads)
}

per_cell_adt_qc_metrics <- function(x, subsets, nthreads) {
    .Call('_scran_chan_per_cell_adt_qc_metrics', PACKAGE = 'scran.chan', x, subsets, nthreads)
}

per_cell_crispr_qc_metrics <- function(x, nthreads) {
    .Call('_scran_chan_per_cell_crispr_qc_metrics', PACKAGE = 'scran.chan', x, nthreads)
}

per_cell_rna_qc_metrics <- function(x, subsets, nthreads) {
    .Call('_scran_chan_per_cell_rna_qc_metrics', PACKAGE = 'scran.chan', x, subsets, nthreads)
}

tatami_dim <- function(x) {
    .Call('_scran_chan_tatami_dim', PACKAGE = 'scran.chan', x)
}

tatami_rows <- function(x, rows, first, last) {
    .Call('_scran_chan_tatami_rows', PACKAGE = 'scran.chan', x, rows, first, last)
}

tatami_columns <- function(x, columns, first, last) {
    .Call('_scran_chan_tatami_columns', PACKAGE = 'scran.chan', x, columns, first, last)
}

run_blocked_pca <- function(x, ndim, batch, features, scale, rotation, nthreads) {
    .Call('_scran_chan_run_blocked_pca', PACKAGE = 'scran.chan', x, ndim, batch, features, scale, rotation, nthreads)
}

run_multibatch_pca <- function(x, ndim, batch, features, scale, rotation, nthreads) {
    .Call('_scran_chan_run_multibatch_pca', PACKAGE = 'scran.chan', x, ndim, batch, features, scale, rotation, nthreads)
}

run_pca <- function(x, ndim, features, scale, rotation, nthreads) {
    .Call('_scran_chan_run_pca', PACKAGE = 'scran.chan', x, ndim, features, scale, rotation, nthreads)
}

run_tsne <- function(nnidx, nndist, perplexity, interpolate, max_depth, max_iter, seed, nthreads) {
    .Call('_scran_chan_run_tsne', PACKAGE = 'scran.chan', nnidx, nndist, perplexity, interpolate, max_depth, max_iter, seed, nthreads)
}

perplexity_to_neighbors <- function(p) {
    .Call('_scran_chan_perplexity_to_neighbors', PACKAGE = 'scran.chan', p)
}

run_umap <- function(nnidx, nndist, min_dist, seed, num_epochs, nthreads) {
    .Call('_scran_chan_run_umap', PACKAGE = 'scran.chan', nnidx, nndist, min_dist, seed, num_epochs, nthreads)
}

scale_by_neighbors <- function(matrices, k, approximate, nthreads) {
    .Call('_scran_chan_scale_by_neighbors', PACKAGE = 'scran.chan', matrices, k, approximate, nthreads)
}

score_feature_set <- function(x, features, batch, scale, nthreads) {
    .Call('_scran_chan_score_feature_set', PACKAGE = 'scran.chan', x, features, batch, scale, nthreads)
}

score_markers <- function(x, groups, batch, simple_means_only, lfc, nthreads) {
    .Call('_scran_chan_score_markers', PACKAGE = 'scran.chan', x, groups, batch, simple_means_only, lfc, nthreads)
}

subset_matrix <- function(x, i, j) {
    .Call('_scran_chan_subset_matrix', PACKAGE = 'scran.chan', x, i, j)
}

suggest_adt_qc_filters <- function(sums, detected, subsets, batch, nmads) {
    .Call('_scran_chan_suggest_adt_qc_filters', PACKAGE = 'scran.chan', sums, detected, subsets, batch, nmads)
}

suggest_crispr_qc_filters <- function(sums, max_prop, batch, nmads) {
    .Call('_scran_chan_suggest_crispr_qc_filters', PACKAGE = 'scran.chan', sums, max_prop, batch, nmads)
}

suggest_rna_qc_filters <- function(sums, detected, subsets, batch, nmads) {
    .Call('_scran_chan_suggest_rna_qc_filters', PACKAGE = 'scran.chan', sums, detected, subsets, batch, nmads)
}

