# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_nn_index <- function(data) {
    .Call('_scran_chan_build_nn_index', PACKAGE = 'scran.chan', data)
}

build_graph <- function(nnptr, k, nthreads) {
    .Call('_scran_chan_build_graph', PACKAGE = 'scran.chan', nnptr, k, nthreads)
}

cluster_multilevel <- function(ptr, res) {
    .Call('_scran_chan_cluster_multilevel', PACKAGE = 'scran.chan', ptr, res)
}

filter_cells <- function(x, discard) {
    .Call('_scran_chan_filter_cells', PACKAGE = 'scran.chan', x, discard)
}

initialize_from_sparse <- function(x, i, p, nrow, ncol) {
    .Call('_scran_chan_initialize_from_sparse', PACKAGE = 'scran.chan', x, i, p, nrow, ncol)
}

initialize_from_blocks <- function(indices, values, nrow, ncols, nthreads) {
    .Call('_scran_chan_initialize_from_blocks', PACKAGE = 'scran.chan', indices, values, nrow, ncols, nthreads)
}

log_norm_counts <- function(x, size_factors) {
    .Call('_scran_chan_log_norm_counts', PACKAGE = 'scran.chan', x, size_factors)
}

model_gene_var <- function(x, span, nthreads) {
    .Call('_scran_chan_model_gene_var', PACKAGE = 'scran.chan', x, span, nthreads)
}

per_cell_qc_filters <- function(sums, detected, subsets, nmads) {
    .Call('_scran_chan_per_cell_qc_filters', PACKAGE = 'scran.chan', sums, detected, subsets, nmads)
}

per_cell_qc_metrics <- function(x, subsets, nthreads) {
    .Call('_scran_chan_per_cell_qc_metrics', PACKAGE = 'scran.chan', x, subsets, nthreads)
}

tatami_dim <- function(x) {
    .Call('_scran_chan_tatami_dim', PACKAGE = 'scran.chan', x)
}

tatami_rows <- function(x, rows, first, last) {
    .Call('_scran_chan_tatami_rows', PACKAGE = 'scran.chan', x, rows, first, last)
}

tatami_columns <- function(x, columns, first, last) {
    .Call('_scran_chan_tatami_columns', PACKAGE = 'scran.chan', x, columns, first, last)
}

run_pca <- function(x, ndim, features, nthreads) {
    .Call('_scran_chan_run_pca', PACKAGE = 'scran.chan', x, ndim, features, nthreads)
}

initialize_tsne <- function(nnptr, perplexity, nthreads) {
    .Call('_scran_chan_initialize_tsne', PACKAGE = 'scran.chan', nnptr, perplexity, nthreads)
}

run_tsne <- function(init, nthreads) {
    .Call('_scran_chan_run_tsne', PACKAGE = 'scran.chan', init, nthreads)
}

initialize_umap <- function(nnptr, num_neighbors, nthreads) {
    .Call('_scran_chan_initialize_umap', PACKAGE = 'scran.chan', nnptr, num_neighbors, nthreads)
}

run_umap <- function(init) {
    .Call('_scran_chan_run_umap', PACKAGE = 'scran.chan', init)
}

