# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_qc_metrics <- function(x, subsets) {
    .Call('_diet_scran_compute_qc_metrics', PACKAGE = 'diet.scran', x, subsets)
}

